name: CI Pipeline with Log Output

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install > build-log.txt 2>&1

    - name: Run build
      run: |
        npm run build >> build-log.txt 2>&1 || echo "Build failed, check build-log.txt"

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build-log.txt
